create table client(
       id int primary key generated by default as identity,
       name varchar(18) NOT NULL,
       age int,
       password varchar(96) NOT NULL,
       email varchar NOT NULL,
       drivingExperience int,
       role varchar(20)
)

