CREATE TYPE role AS ENUM('GUEST', 'USER', 'ADMIN');

create table clients(
        client_id int primary key generated by default as identity,
        name varchar(30) NOT NULL,
        age int,
        password varchar(100) NOT NULL,
        email varchar NOT NULL,
        drivingExperience int,
        role role NOT NULL
)